# Rosé Pine Moon
# https://rosepinetheme.com

tmux_conf_theme_colour_1="#232136"    # base
tmux_conf_theme_colour_2="#2a273f"    # surface
tmux_conf_theme_colour_3="#6e6a86"    # muted
tmux_conf_theme_colour_4="#9ccfd8"    # foam
tmux_conf_theme_colour_5="#f6c177"    # gold
tmux_conf_theme_colour_6="#232136"    # base
tmux_conf_theme_colour_7="#e0def4"    # text
tmux_conf_theme_colour_8="#232136"    # base
tmux_conf_theme_colour_9="#c4a7e7"    # iris
tmux_conf_theme_colour_10="#ea9a97"   # rose
tmux_conf_theme_colour_11="#3e8fb0"   # pine
tmux_conf_theme_colour_12="#908caa"   # subtle
tmux_conf_theme_colour_13="#e0def4"   # text
tmux_conf_theme_colour_14="#232136"   # base
tmux_conf_theme_colour_15="#232136"   # base
tmux_conf_theme_colour_16="#eb6f92"   # love
tmux_conf_theme_colour_17="#e0def4"   # text
